name: iOS Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        sudo xcodebuild -runFirstLaunch

    - name: Install Dependencies
      run: |
        xcrun simctl list
        
    - name: Build and Test
      run: xcodebuild -scheme "Movies" -destination "platform=iOS Simulator,id=437E5131-A475-496C-8B52-5909985A90FB,OS=17.2,name=iPhone 15" test
