name: iOS Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        sudo xcodebuild -runFirstLaunch

    - name: Install Dependencies
      run: |
        xcrun simctl list
        
    - name: Build and Test
      run: xcodebuild test -scheme Movies -project Movies.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 15,OS=17' | xcpretty && exit ${PIPESTATUS[0]} 
