name: iOS Tests

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ] 

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install Dependencies
      run: |
        xcrun simctl list

    - name: List Simulators
      run: xcrun simctl list devices

    - name: Build and Test
      run: xcodebuild -scheme "Movies" -destination "platform=iOS,name=Iphone 15" test
