name: iOS Tests

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ] 

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        sudo xcodebuild -runFirstLaunch

    - name: Install Dependencies
      run: |
        xcrun simctl list

    - name: List Simulators
      run: xcrun simctl list devices

    - name: Build and Test
      run: xcodebuild -scheme "Movies" -destination "platform=iOS Simulator,name=Any iOS Simulator Device" test
