name: Swift

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  Run_workspace_Tests:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.2.app && /usr/bin/xcodebuild -version
    - name: Set up Info.plist
      uses: damienaicheh/update-ios-version-info-plist-action@v1.0.0
      with:
        plist-path: 'Movies/Info.plist'
    - name: Run unit tests
      run: xcodebuild clean test -scheme Movies -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' | xcpretty && exit ${PIPESTATUS[0]}

