name: iOS Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    container:
      image: swift:latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Build and Test
      run: |
        swift test
